### PR TITLE
parse url subroutes as they are read from Gm.jl

### PR DESCRIPTION
**Pull request by cdrani**
Used re module to retrieve only the url subroutes like `/games/switch/gris` and concat it with the root url, resulting in `https://www.metacritic.com/games/switch/gris`.

### CODE REVIEW

**Comment by Markel** [comment]
Oh, that seems a great idea, I will revise it as fast a I can!

**Comment by Markel** [comment]
Nah, don't worry, mistakes always occur. For that we have git, for revising code so we can correct these mistakes 😄 (and for other many things too!). Btw, it works very well, I'm going to double check everything and I will merge it soon (apart from that I have to modify instructions, etc). For curiosity, what are you going to use the repository for?

**Comment by Markel** [comment]
Ups 😅 I closed it by error 😅😂

**Comment by cdrani** [comment]
I was just looking at repos that made use of a scraper. I prefer reading source code sometimes over docs. Initially I was going to build one using nodejs, but it would work just as well with python or ruby. This happened to be good example and was quite readable even though I had not used python in a long time.

**Comment by Markel** [comment]
Oh, glad it helped you and thank you very much for making this project better ^^.

**Review by Markel — APPROVED** [review]
The edits work perfectly, now we don't need to format manually the gm.jl 🎉🥳. Some of the instructions will be updated soon to reflect these changes (especially the readme). Thank you very much, I'm merging it now.

**Pull request merged**
