### PR TITLE
:apple: conditional rendering on win32 only on windows

### PR DESCRIPTION
**Pull request by cdrani**
Currently it immediately throws an error on macos and most likely linux

### CODE REVIEW

**Comment by Markel** [comment]
🤔 I'm thinking, do we really need `win32api` anyway? I have tested both scripts (stopping the scraper at 500 games) deleting the import of win32api and they worked perfectly. I don't know, maybe I have skipped something, but I think that we could simply delete the import request.

**Comment by cdrani** [comment]
Ok. I only have it because I assumed you need it to run on windows. If it's not required I can remove it.

**Comment by Markel** [comment]
Yeah, remove it.

**Review by Markel — APPROVED** [review]
Perfect!

**Pull request merged**
